apiVersion: v2
name: ingress-nginx
description: A Helm chart for Kubernetes
type: application
version: 4.13.2
dependencies:
  - name: ingress-nginx
    version: 4.13.2
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingress-nginx.enabled