apps:
  argo-rollouts:
    namespace: argo-rollouts
    chart: argo-rollouts
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 2.40.4
    helm:
      releaseName: argo-rollouts
      values:
        metrics:
          enabled: true
          serviceMonitor:
            enabled: true
            additionalLabels:
              release: kube-prometheus-stack
  kube-prometheus-stack:
    namespace: monitoring
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 77.10.0
    helm:
      releaseName: kube-prometheus-stack
      values: 
        crds:
          enabled: true
          upgradeJob:
            enabled: true
            forceConflicts: true
        alertmanager:
          podDisruptionBudget:
            enabled: true
          alertmanagerSpec:
            replicas: 2            
        prometheus:
          podDisruptionBudget:
            enabled: true
          prometheusSpec:
            replicas: 2
        grafana:
          additionalDataSources:
          - name: loki-logs
            access: proxy
            # basicAuth: true
            # secureJsonData:
            #     basicAuthPassword: pass
            # basicAuthUser: daco
            # editable: false
            # jsonData:
            #     tlsSkipVerify: true
            # orgId: 1
            type: loki
            url: http://loki.loki:3100/
            version: 1
  cert-manager:
    namespace: cert-manager
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: v1.18.2
    helm:
      releaseName: cert-manager
      values:
        installCRDs: true
        replicaCount: 3