apps:
  argo-rollouts:
    namespace: argo-rollouts
    chart: argo-rollouts
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 2.40.4
    helm:
      releaseName: argo-rollouts
  kube-prometheus-stack:
    namespace: monitoring
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 77.10.0
    helm:
      releaseName: kube-prometheus-stack
      values: 
        crds:
          enabled: true
          upgradeJob:
            enabled: true
            forceConflicts: true
        alertmanager:
          podDisruptionBudget:
            enabled: true
          alertmanagerSpec:
            replicas: 2            
        prometheus:
          podDisruptionBudget:
            enabled: true
          prometheusSpec:
            replicas: 2